name: CI

on: 
  push: 
    branches: 
      - main
    paths:
      # - 'api/**'
      - '.github/workflows/ci.yml'

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
    
jobs:
  build:
    name: "Build and push"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup node
        uses: actions/setup-node@v5
        with: 
          node-version: 22
          cache: npm
          cache-dependency-path: api/package-lock.json
      
      - run: npm i
      - run: npm run test


      - name: Semantic Release 
        uses: cycjimmy/semantic-release-action@v6
        with:
          working_directory: ./api

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with: 
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::831181104004:role/ecr_role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build docker image
        id: build-docker-image
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          TAG: ${{steps.generate_tag.outputs.sha}}
        run: |
          docker build -t $REGISTRY/cicd_estudos:$TAG .
          docker push $REGISTRY/cicd_estudos:$TAG
          IMAGE=$(echo $REGISTRY/cicd_estudos:$TAG)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT


      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with: 
          image: ${{steps.build-docker-image.outputs.image}}
          service: api-cicd-estudos
          access-role-arn: arn:aws:iam::831181104004:role/app_runner_role
          region: us-east-2
          cpu: 1
          memory: 2
          port: 3000
          wait-for-service-stability-seconds: 300

      # - name: Push Image
      #   run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ci-cd-estudos:${{steps.generate_tag.outputs.sha}}
