name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'iac/**'
      - '.github/workflows/iac.ci.yml'

permissions: 
  id-token: write
  contents: read

jobs:
  run-terraform:
    name: "Run Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./iac

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{secrets.REGION}}
          role-to-assume: ${{secrets.ARN_ROLE_TF_ROLE}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform plan
        env:
          TF_VAR_profile: ${{ secrets.PROFILE }}
          TF_VAR_region: ${{ secrets.REGION }}
        run: terraform plan -input=false

      - name: Terraform apply
        run: terraform apply -auto-approve
